version: "3.9"

services:
  #  app:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - petdb
  #    restart: always
  #

  petdb:
    image: postgres:12
    volumes:
      - petdb-app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  petdb-app-db-data:
